### ISSUE TITLE
Replace subfields within dag's default_args instead of the whole thing

### ISSUE THREAD

**Issue by timkpaine** [airflow-laminar/airflow-config#47]
https://github.com/airflow-laminar/airflow-config/blob/5fe1f289cd33bba4ab9ebba8615d5ae47a729e45/airflow_config/configuration/base.py#L143

In the below example, `example-dag` should have `owner=tim, retries=0` but currently `default_args` will clobber so it will have `retries=0` but `owner=airflow`.

```yaml
_target_: airflow_config.Configuration

default_args:
  _target_: airflow_config.TaskArgs
  owner: tim
  retries: 5

dags:
  example-dag:
    dag_id: example-dag
    description: A simple DAG
    schedule: "0 9 * * *"
    tags: [example]
    default_args:
        retries: 0
```
